server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: match-history
          uri: http://localhost:8081
          predicates:
            - Path=/match/**
        - id: ranking
          uri: http://localhost:8082
          predicates:
            - Path=/ranking/**
